name: macos

on: [push, pull_request]

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15]
        build_type: [Release, Debug]

    name: "${{ matrix.os }} / ${{ matrix.build_type }}"
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build build --parallel

    - name: Test
      run: ctest --test-dir build --output-on-failure
