name: windows

on: [push, pull_request]

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, windows-2025]
        config: [Release, Debug]

    name: "${{ matrix.os }} / x64 / ${{ matrix.config }}"
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: cmake -S . -B build -A x64

    - name: Build
      run: cmake --build build --parallel --config ${{ matrix.config }}

    - name: Test
      run: ctest --test-dir build --output-on-failure -C ${{ matrix.config }}
